# Generated by Django 4.1 on 2022-09-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
