# Generated by Django 4.1 on 2022-09-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_stats_end_date_alter_stats_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='stats',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
