# Generated by Django 4.1 on 2022-09-15 09:48

from django.db import migrations
import enumchoicefield.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='metric',
            field=enumchoicefield.fields.EnumChoiceField(default=product.models.Metric(1), enum_class=product.models.Metric, max_length=5),
        ),
    ]
